### ISSUE TITLE
gitub link not working

### ISSUE THREAD

**Issue by jungwonshin** [stereolabs/zed-unity#301]
### Preliminary Checks

- [x] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [x] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

When I add the package git url, the unity shuts down. Please fix this.

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

It should be installed on Unity

### Actual Result

Unity Crashes

### ZED Camera model

ZED

### Environment

```shell
OS: windows
```

**Comment by Bvallon-sl** [comment]
Hi,

Thanks for reporting. It seems the Unity project crashes at start if there is a version mismatch between the plugin and the SDK version installed on your machine. I'll investigate further this week and see what exactly is causing this.

Sorry for the inconvenience.

**Comment by jungwonshin** [comment]
I tried new project and now the program doesn't crash but getting this error despite zed sdk being latest version.

![Image](https://github.com/user-attachments/assets/42fe4558-f764-4f41-adc3-fcfa1ba2db95)

**Comment by Bvallon-sl** [comment]
It should be fixed now, can you confirm?

**Comment by vincenzorin** [comment]
Updating this issue as it appears to be still present today.

I was having issues with Unity 6000.0.70 and 72f1, where Unity would crash upon installing the SDK via the suggested workflow (install package via the Git link).

The Unity project crashes every time I run it, at the very beginning. It becomes usable again if I remove the following lines:
1. From "C:\xxx\Packages\manifest.json", the following package:
`"com.stereolabs.zed": "https://github.com/stereolabs/zed-unity.git?path=/ZEDCamera/Assets"`
2. From "C:\xxx\Packages\packages-lock.json", the following dependency:
`"com.stereolabs.zed": {
      "version": "https://github.com/stereolabs/zed-unity.git?path=/ZEDCamera/Assets",
      "depth": 0,
      "source": "git",
      "dependencies": {
        "com.unity.xr.management": "4.4.0",
        "com.unity.ugui": "1.0.0",
        "com.unity.modules.animation": "1.0.0",
        "com.unity.modules.imageconversion": "1.0.0"
      },
      "hash": "..."
    },`


I currently have ZED SDK version 5.1.0 installed on my system.
I previously gradually upgraded from 5.0.5 (if I'm not wrong) up to 5.2. I had to roll back from 5.2 to 5.1.0 due to incompatibility with the recording device, which is currently at 5.1.
